name: "Protocol Buffers Go Stubs Generation"
on:
  push:
    tags: 
      - v**
permissions: 
  contents: write
jobs:
  protoc:
    name: "Generate"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ["order", "payment", "shipping"]
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - name: Setup Project
        uses: actions/checkout@v4
      - name: Extract Release Version
        run: |
          echo "RELEASE VERSION: ${GITHUB_REF#refs/*/}"
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Generate For Golang
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          echo "Token first 4 chars: ${GITHUB_TOKEN:0:4}..."
          echo "Remote URL: $(git remote get-url origin | sed 's/x-access-token:[^@]*@/x-access-token:****@/')"
          echo "workspace: ${GITHUB_WORKSPACE}"
          chmod +x "${GITHUB_WORKSPACE}/run.sh"                           
          ./run.sh ${{ matrix.service}} ${{ env.RELEASE_VERSION }} 
