name: "Protocol Buffer Go Stubs Generation"
on:
  workflow_dispatch:
permissions: 
  contents: write
jobs:
  protoc:
    name: "Generate"
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - uses: actions/checkout@v4
      - name: "Generate for Golang"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sudo apt-get install -y protobuf-compiler golang-goprotobuf-dev
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
          mkdir -p golang
          protoc --go_out=./golang --go_opt=paths=source_relative --go-grpc_out=./golang --go-grpc_opt=paths=source_relative ./**/*.proto
          git config --global user.email "saisailuhlaing@gmail.com"
          git config --global user.name "SaiHLu"
          git add .
          git commit -am "proto update"
          git config --remote.origin.url https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/SaiHLu/microservices-proto.git
          git push origin main